### ISSUE TITLE
package:discover fails

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-cli#11]
When trying to run `osjs-cli package:discover`, this error appeared:
```
> @bluelightos/osjs@3.0.0-beta.11 package:discover /home/spaceboyross/Projects/pacman-repo/bluelight-base/pkg/bluelight-base/opt/os.js
> osjs-cli package:discover

/home/spaceboyross/Projects/pacman-repo/bluelight-base/pkg/bluelight-base/opt/os.js/node_modules/ajv/lib/keyword.js:65
      throw new Error('custom keyword definition is invalid: '  + this.errorsText(validateDefinition.errors));
      ^

Error: custom keyword definition is invalid: data/errors should be boolean
    at Ajv.addKeyword (/home/spaceboyross/Projects/pacman-repo/bluelight-base/pkg/bluelight-base/opt/os.js/node_modules/ajv/lib/keyword.js:65:13)
    at module.exports (/home/spaceboyross/Projects/pacman-repo/bluelight-base/pkg/bluelight-base/opt/os.js/node_modules/ajv-errors/index.js:10:7)
    at Object.<anonymous> (/home/spaceboyross/Projects/pacman-repo/bluelight-base/pkg/bluelight-base/opt/os.js/node_modules/schema-utils/src/validateOptions.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bluelightos/osjs@3.0.0-beta.11 package:discover: `osjs-cli package:discover`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @bluelightos/osjs@3.0.0-beta.11 package:discover script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spaceboyross/.npm/_logs/2019-02-10T01_05_53_646Z-debug.log
```

**Comment by andersevenrud** [comment]
This is because an update of `ajv` broke webpack:

https://github.com/webpack/webpack/issues/8768

**Comment by andersevenrud** [comment]
Seems to have been resolved in: https://github.com/epoberezkin/ajv/issues/941

Try running `npm update`, then try again :)
